version: "2.1"
services:
  app:
    build: .
    restart: unless-stopped
    networks:
      - flask-backend-tier
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql://admin:12345678@db/chicago_dish"
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "32000:3306"
    networks:
      - flask-backend-tier
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    environment:
      - MYSQL_DATABASE=chicago_dish
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

networks:
  flask-backend-tier:
    driver: bridge
